// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Top10Trab.Data;

namespace Top10Trab.Migrations
{
    [DbContext(typeof(DBTop10Contexto))]
    partial class DBTop10ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Top10Trab.Models.Jogador", b =>
                {
                    b.Property<int>("JogadorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Idade");

                    b.Property<string>("Nacionalidade");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("JogadorID");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("Top10Trab.Models.Placar", b =>
                {
                    b.Property<int>("PlacarID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data");

                    b.Property<int>("JogadorID");

                    b.Property<int>("Pontuacao");

                    b.HasKey("PlacarID");

                    b.HasIndex("JogadorID");

                    b.ToTable("Placares");
                });

            modelBuilder.Entity("Top10Trab.Models.Placar", b =>
                {
                    b.HasOne("Top10Trab.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
